### ISSUE TITLE
function initialize

### ISSUE THREAD

**Issue by ohbin-kwon** [charmingpark/wedding-invitation-EverEverAfter#11]
#8 의 repository 53번째 줄을 보면 FakeRepo([])로  initialize를 하는데, 위에서 인자를 []로 init해주는데 다시 []로 init하는 이유가 있는지 궁금합니다.
comment같은 경우는 인자에서 init을 하고, export할때는 해당함수의 호출해 주었더니 잘작동해서, 굳이 init할때 저렇게 []로 init한 이유가 있는지 궁금합니다

`
export function FakeRepo(init: PostT[] = []): PostRepository {
  let _fakeDB = init;
  let _count = Math.max(0, ...init.map(post => post.id));
  ...

export const fakeRepo: PostRepository = FakeRepo([]);

`

**Comment by twinstae** [comment]
사실 이거는 default로 넣어주는 []를 없애 버리는 게 맞겠습니다. Fake는 테스트용으로 쓰이는데. 테스트에서는 명시적으로 초기 데이터를 보여주는 것이 더 좋기 때문입니다.

**Comment by ohbin-kwon** [comment]
테스트 시 생성자로 []를 주입해 보도록 하겠습니다
