### ISSUE TITLE
import function vs module

### ISSUE THREAD

**Issue by ohbin-kwon** [charmingpark/wedding-invitation-EverEverAfter#12]
repository에서 FakeRepo로 함수선언식을 export 하는경우와 fakerepo로 호출한 함수를 export하는경우의 차이점에 대해 이야기해보고싶습니다. 작성하고 보니 이전 issue와 연관될것같은 이슈네요

**Comment by twinstae** [comment]
생성자 함수를 export하는 것은 자바 같은 언어로 치면 클래스를 export하는 것과 같습니다.

반면에 이미 생성된 instance를 export하는 건 실제 의존성을 주입하는 것과 같습니다. 이렇게 생성된 인스턴스는 모든 앱에서 하나를 공유하는 전역 상태입니다. 매 테스트마다 새로 생성해줄 수도 없고 번거롭지요.

**Comment by ohbin-kwon** [comment]
그렇다면 생성자 함수를 export하는것이 상황에 맞게 의존성 주입을 해줄 수 있기 때문에 목적에 더 맞다고 생각하면 되겠군요
